# Generated by Django 2.2.6 on 2019-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='password',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
